# Kayfa Task 1 - Employee Attrition Analytics 📊

**The Business Question:**
>Why are employees leaving the company, and which employee groups have the highest attrition risk?

## Imports

In [ ]:
import os
import kagglehub
import pandas as pd
import plotly.express as px
from IPython.display import display
import plotly.graph_objects as go
from plotly.subplots import make_subplots

## Download and scan dataset

In [ ]:
path = kagglehub.dataset_download("stealthtechnologies/employee-attrition-dataset")
files = os.listdir(path)
print("Files in dataset folder:", files)

Using Colab cache for faster access to the 'employee-attrition-dataset' dataset.
Files in dataset folder: ['train.csv', 'test.csv']

## Load the training data

In [ ]:
train_path = os.path.join(path, 'train.csv')
train = pd.read_csv(train_path)
print("---Head---")
train.head()

---Head---

,Employee ID,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,...,Number of Dependents,Job Level,Company Size,Company Tenure,Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition,Attrition
0,8410,31,Male,19,Education,5390,Excellent,Medium,Average,2,...,0,Mid,Medium,89,No,No,No,Excellent,Medium,Stayed
1,64756,59,Female,4,Media,5534,Poor,High,Low,3,...,3,Mid,Medium,21,No,No,No,Fair,Low,Stayed
2,30257,24,Female,10,Healthcare,8159,Good,High,Low,0,...,3,Mid,Medium,74,No,No,No,Poor,Low,Stayed
3,65791,36,Female,7,Education,3989,Good,High,High,1,...,2,Mid,Small,50,Yes,No,No,Good,Medium,Stayed
4,65026,56,Male,41,Education,4821,Fair,Very High,Average,0,...,0,Senior,Medium,68,No,No,No,Fair,Medium,Stayed

## Load the testing data

In [ ]:
test_path = os.path.join(path, 'test.csv')
test = pd.read_csv(test_path)
test.head()

,Employee ID,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,...,Number of Dependents,Job Level,Company Size,Company Tenure,Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition,Attrition
0,52685,36,Male,13,Healthcare,8029,Excellent,High,Average,1,...,1,Mid,Large,22,No,No,No,Poor,Medium,Stayed
1,30585,35,Male,7,Education,4563,Good,High,Average,1,...,4,Entry,Medium,27,No,No,No,Good,High,Left
2,54656,50,Male,7,Education,5583,Fair,High,Average,3,...,2,Senior,Medium,76,No,No,Yes,Good,Low,Stayed
3,33442,58,Male,44,Media,5525,Fair,Very High,High,0,...,4,Entry,Medium,96,No,No,No,Poor,Low,Left
4,15667,39,Male,24,Education,4604,Good,High,Average,0,...,6,Mid,Large,45,Yes,No,No,Good,High,Stayed

## Combine the train and test csvs

In [ ]:
df = pd.concat([train, test], ignore_index=True)
display(df.head())
df.tail()

,Employee ID,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,...,Number of Dependents,Job Level,Company Size,Company Tenure,Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition,Attrition
0,8410,31,Male,19,Education,5390,Excellent,Medium,Average,2,...,0,Mid,Medium,89,No,No,No,Excellent,Medium,Stayed
1,64756,59,Female,4,Media,5534,Poor,High,Low,3,...,3,Mid,Medium,21,No,No,No,Fair,Low,Stayed
2,30257,24,Female,10,Healthcare,8159,Good,High,Low,0,...,3,Mid,Medium,74,No,No,No,Poor,Low,Stayed
3,65791,36,Female,7,Education,3989,Good,High,High,1,...,2,Mid,Small,50,Yes,No,No,Good,Medium,Stayed
4,65026,56,Male,41,Education,4821,Fair,Very High,Average,0,...,0,Senior,Medium,68,No,No,No,Fair,Medium,Stayed

,Employee ID,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,...,Number of Dependents,Job Level,Company Size,Company Tenure,Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition,Attrition
74493,16243,56,Female,42,Healthcare,7830,Poor,Medium,Average,0,...,0,Senior,Medium,60,No,No,No,Poor,Medium,Stayed
74494,47175,30,Female,15,Education,3856,Good,Medium,Average,2,...,0,Entry,Medium,20,No,No,No,Good,Medium,Left
74495,12409,52,Male,5,Education,5654,Good,Very High,Below Average,0,...,4,Mid,Small,7,No,No,No,Good,High,Left
74496,9554,18,Male,4,Education,5276,Fair,High,Average,0,...,3,Mid,Large,5,No,No,No,Poor,High,Stayed
74497,73042,59,Female,48,Education,3774,Good,High,Below Average,1,...,4,Mid,Large,118,No,No,No,Good,Very High,Left

In [ ]:
print("Shape of train df:", train.shape)
print("Shape of test df:",test.shape)
print("Shape of whole df:",df.shape)
print("\n---info---")
df.info()
print("\n---description---")
df.describe()

Shape of train df: (59598, 24)
Shape of test df: (14900, 24)
Shape of whole df: (74498, 24)

---info---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74498 entries, 0 to 74497
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Employee ID               74498 non-null  int64
 1   Age                       74498 non-null  int64
 2   Gender                    74498 non-null  object
 3   Years at Company          74498 non-null  int64
 4   Job Role                  74498 non-null  object
 5   Monthly Income            74498 non-null  int64
 6   Work-Life Balance         74498 non-null  object
 7   Job Satisfaction          74498 non-null  object
 8   Performance Rating        74498 non-null  object
 9   Number of Promotions      74498 non-null  int64
 10  Overtime                  74498 non-null  object
 11  Distance from Home        74498 non-null  int64
 12  Education Level           74498 non-null  object
 13  Marital Status            74498 non-null  object
 14  Number of Dependents      74498 non-null  int64
 15  Job Level                 74498 non-null  object
 16  Company Size              74498 non-null  object
 17  Company Tenure            74498 non-null  int64
 18  Remote Work               74498 non-null  object
 19  Leadership Opportunities  74498 non-null  object
 20  Innovation Opportunities  74498 non-null  object
 21  Company Reputation        74498 non-null  object
 22  Employee Recognition      74498 non-null  object
 23  Attrition                 74498 non-null  object
dtypes: int64(8), object(16)
memory usage: 13.6+ MB

---describtion---

,Employee ID,Age,Years at Company,Monthly Income,Number of Promotions,Distance from Home,Number of Dependents,Company Tenure
count,74498.000000,74498.000000,74498.000000,74498.000000,74498.000000,74498.000000,74498.000000,74498.000000
mean,37249.500000,38.529746,15.721603,7299.379514,0.832935,49.991584,1.650326,55.727456
std,21505.864514,12.083456,11.223744,2152.508566,0.995289,28.513611,1.553633,25.399349
min,1.000000,18.000000,1.000000,1226.000000,0.000000,1.000000,0.000000,2.000000
25%,18625.250000,28.000000,7.000000,5652.000000,0.000000,25.000000,0.000000,36.000000
50%,37249.500000,39.000000,13.000000,7348.000000,1.000000,50.000000,1.000000,56.000000
75%,55873.750000,49.000000,23.000000,8876.000000,2.000000,75.000000,3.000000,76.000000
max,74498.000000,59.000000,51.000000,16149.000000,4.000000,99.000000,6.000000,128.000000

## Copy and Normalize column names to snake_case

## Red Flags from describe table
1.   Age
2.   Years at the company
3.   Company Tenure

In [ ]:
df[["Years at Company", "Company Tenure"]].head(20)

    Years at Company  Company Tenure
0                 19              89
1                  4              21
2                 10              74
3                  7              50
4                 41              68
5                  3              47
6                 23              93
7                 16              88
8                 44              75
9                  1              45
10                12              17
11                 6              38
12                38              68
13                22              84
14                30              96
15                 4              21
16                 9              63
17                 1              19
18                37              70
19                 9              76

In [ ]:
df["starting_age"] = df["Age"] - df["Years at Company"]
df["starting_age"].describe()

count    74498.000000
mean        22.808143
std         11.235584
min          8.000000
25%         14.000000
50%         20.000000
75%         30.000000
max         58.000000
Name: starting_age, dtype: float64

## ابن الشركه من وهو 8 سنين

In [ ]:
print((df["starting_age"] < 18).sum())
print((df["starting_age"] < 16).sum())
print((df["starting_age"] == 8 ).sum())
print((df["starting_age"] < 8 ).sum())

29812
23902
2978
0

In [ ]:
print((df["Company Tenure"] > 80 ).sum())
print((df["Company Tenure"] > 100 ).sum())
print((df["Company Tenure"] > 120 ).sum())
print((df["Company Tenure"] == 128 ).sum())

13934
2548
88
1

In [ ]:
impossible_count = (df['Years at Company'] > df['Age']).sum()
print(f"Rows where tenure is physically greater than age: {impossible_count}")

Rows where tenure is physically greater than age: 0

# Preprocessing & Cleaning 🧼🧹

## Copy and Normalize column names to `snake_case`

In [ ]:
df_cleaned = df.copy()
df_cleaned.columns = (
    df_cleaned.columns
      .str.lower()
      .str.strip()
      .str.replace(" ", "_")
      .str.replace('-', '_')
)

## Data Quality checks:
*   missing values
*   duplicates
*   empty strings
*   column cleanup

In [ ]:
display(df_cleaned.isnull().sum())
display(df_cleaned.duplicated().sum())
display((df_cleaned.astype(str).apply(lambda x: x.str.strip()) == '').sum())

employee_id                 0
age                         0
gender                      0
years_at_company            0
job_role                    0
monthly_income              0
work_life_balance           0
job_satisfaction            0
performance_rating          0
number_of_promotions        0
overtime                    0
distance_from_home          0
education_level             0
marital_status              0
number_of_dependents        0
job_level                   0
company_size                0
company_tenure              0
remote_work                 0
leadership_opportunities    0
innovation_opportunities    0
company_reputation          0
employee_recognition        0
attrition                   0
dtype: int64

np.int64(0)

employee_id                 0
age                         0
gender                      0
years_at_company            0
job_role                    0
monthly_income              0
work_life_balance           0
job_satisfaction            0
performance_rating          0
number_of_promotions        0
overtime                    0
distance_from_home          0
education_level             0
marital_status              0
number_of_dependents        0
job_level                   0
company_size                0
company_tenure              0
remote_work                 0
leadership_opportunities    0
innovation_opportunities    0
company_reputation          0
employee_recognition        0
attrition                   0
dtype: int64

In [ ]:
df_cleaned.drop("employee_id", axis=1, inplace=True)

## Verify Category Values

In [ ]:
for col in df_cleaned.select_dtypes(include="object"):
    print(col)
    print(df_cleaned[col].unique())

gender
['Male' 'Female']
job_role
['Education' 'Media' 'Healthcare' 'Technology' 'Finance']
work_life_balance
['Excellent' 'Poor' 'Good' 'Fair']
job_satisfaction
['Medium' 'High' 'Very High' 'Low']
performance_rating
['Average' 'Low' 'High' 'Below Average']
overtime
['No' 'Yes']
education_level
['Associate Degree' 'Master’s Degree' 'Bachelor’s Degree' 'High School'
 'PhD']
marital_status
['Married' 'Divorced' 'Single']
job_level
['Mid' 'Senior' 'Entry']
company_size
['Medium' 'Small' 'Large']
remote_work
['No' 'Yes']
leadership_opportunities
['No' 'Yes']
innovation_opportunities
['No' 'Yes']
company_reputation
['Excellent' 'Fair' 'Poor' 'Good']
employee_recognition
['Medium' 'Low' 'High' 'Very High']
attrition
['Stayed' 'Left']

In [ ]:
for col in df_cleaned.select_dtypes(include="object"):
    print(f"\n{'='*40}")
    print(col.upper())
    print(df_cleaned[col].value_counts())

========================================
GENDER
gender
Male      40826
Female    33672
Name: count, dtype: int64

========================================
JOB_ROLE
job_role
Technology    19322
Healthcare    17074
Education     15658
Media         11996
Finance       10448
Name: count, dtype: int64

========================================
WORK-LIFE_BALANCE
work-life_balance
Good         28158
Fair         22529
Excellent    13432
Poor         10379
Name: count, dtype: int64

========================================
JOB_SATISFACTION
job_satisfaction
High         37245
Very High    15079
Medium       14717
Low           7457
Name: count, dtype: int64

========================================
PERFORMANCE_RATING
performance_rating
Average          44719
High             14910
Below Average    11139
Low               3730
Name: count, dtype: int64

========================================
OVERTIME
overtime
No     50157
Yes    24341
Name: count, dtype: int64

========================================
EDUCATION_LEVEL
education_level
Bachelor’s Degree    22331
Associate Degree     18649
Master’s Degree      15021
High School          14680
PhD                   3817
Name: count, dtype: int64

========================================
MARITAL_STATUS
marital_status
Married     37419
Single      26001
Divorced    11078
Name: count, dtype: int64

========================================
JOB_LEVEL
job_level
Entry     29780
Mid       29678
Senior    15040
Name: count, dtype: int64

========================================
COMPANY_SIZE
company_size
Medium    37231
Small     22355
Large     14912
Name: count, dtype: int64

========================================
REMOTE_WORK
remote_work
No     60300
Yes    14198
Name: count, dtype: int64

========================================
LEADERSHIP_OPPORTUNITIES
leadership_opportunities
No     70845
Yes     3653
Name: count, dtype: int64

========================================
INNOVATION_OPPORTUNITIES
innovation_opportunities
No     62394
Yes    12104
Name: count, dtype: int64

========================================
COMPANY_REPUTATION
company_reputation
Good         37182
Poor         15116
Fair         14786
Excellent     7414
Name: count, dtype: int64

========================================
EMPLOYEE_RECOGNITION
employee_recognition
Low          29620
Medium       22657
High         18550
Very High     3671
Name: count, dtype: int64

========================================
ATTRITION
attrition
Stayed    39128
Left      35370
Name: count, dtype: int64

## Encode Ordinal Columns

In [ ]:
ordinal_mappings = {
    "work_life_balance": {"Poor": 0, "Fair": 1, "Good": 2, "Excellent": 3},
    "company_reputation": {"Poor": 0, "Fair": 1, "Good": 2, "Excellent": 3},

    "job_satisfaction": {"Low": 0, "Medium": 1, "High": 2, "Very High": 3},
    "employee_recognition": {"Low": 0, "Medium": 1, "High": 2, "Very High": 3},

    "performance_rating": {"Low": 0, "Below Average": 1, "Average": 2, "High": 3},


    "education_level": {"High School": 0, "Associate Degree": 1, "Bachelor’s Degree": 2, "Master’s Degree": 3, "PhD": 4},

    "job_level": {"Entry": 0, "Mid": 1, "Senior": 2},
    "company_size": {"Small": 0, "Medium": 1, "Large": 2}
}
for col, mapping in ordinal_mappings.items():
    if col in df_cleaned.columns:
        df_cleaned[col] = df_cleaned[col].map(mapping)

## Handle Binary & Target Columns (Yes/No -> 1/0)

In [ ]:
binary_cols = ['overtime', 'remote_work', 'leadership_opportunities', 'innovation_opportunities']
for col in binary_cols:
    if col in df_cleaned.columns:
        df_cleaned[col] = df_cleaned[col].map({'Yes': 1, 'No': 0})

# 6. Map Target column
if 'attrition' in df_cleaned.columns:
    df_cleaned['attrition'] = df_cleaned['attrition'].map({'Left': 1, 'Stayed': 0})

## Address The Anomalies & Feature Engineering (Age & Tenure groups)

In [ ]:
columns_to_drop = ['employee_id', 'company_tenure']
df_cleaned.drop(columns=[col for col in columns_to_drop if col in df_cleaned.columns], inplace=True, errors='ignore')

In [ ]:
df_cleaned['starting_age'] = df_cleaned['age'] - df_cleaned['years_at_company']

age_bins = [0, 29, 44, float('inf')]
age_labels = ['<30 (Young)', '30-44 (Mid-Career)', '45+ (Senior)']
df_cleaned['age_group'] = pd.cut(df_cleaned['age'], bins=age_bins, labels=age_labels)

tenure_bins = [-1, 2, 5, 10, float('inf')]
tenure_labels = ['0-2 years (New)', '2-5 years (Established)', '5-10 years (Loyal)', '10+ years (Veteran)']
df_cleaned['tenure_group'] = pd.cut(df_cleaned['years_at_company'], bins=tenure_bins, labels=tenure_labels)

print("--- Verification Check ---")
print(df_cleaned[['work_life_balance', 'job_satisfaction', 'overtime', 'attrition', 'age_group']].head())

--- Verification Check ---
   work_life_balance  job_satisfaction  overtime  attrition  \
0                  3                 1         0          0
1                  0                 2         0          0
2                  2                 2         0          0
3                  2                 2         0          0
4                  1                 3         1          0

            age_group
0  30-44 (Mid-Career)
1        45+ (Senior)
2         <30 (Young)
3  30-44 (Mid-Career)
4        45+ (Senior)

# EDA 🔎

In [ ]:
attrition_rate = df_cleaned["attrition"].mean() * 100
print(f"Attrition Rate: {attrition_rate:.2f}%")

Attrition Rate: 47.48%

In [ ]:
fig = px.pie(
    df_cleaned,
    names="attrition",
    title="Overall Attrition Distribution",
    color=df_cleaned["attrition"].map({0: "Stayed", 1: "Left"})
)
fig.show()

In [ ]:
job_attrition = df_cleaned.groupby("job_role")["attrition"].mean().sort_values(ascending=False)

fig = px.bar(
    job_attrition,
    title="Attrition Rate by Job Role",
    labels={"value": "Attrition Rate"}
)
fig.show()

In [ ]:
fig = px.bar(
    df_cleaned.groupby("work_life_balance")["attrition"].mean().sort_values(),
    title="Attrition by Work-Life Balance"
)
fig.show()

In [ ]:
fig = px.bar(
    df_cleaned.groupby("job_satisfaction")["attrition"].mean().sort_values(),
    title="Attrition by Job Satisfaction"
)
fig.show()

In [ ]:
fig = px.bar(
    df_cleaned.groupby("job_level")["attrition"].mean(),
    title="Attrition by Job Level"
)
fig.show()

In [ ]:
fig = px.bar(
    df_cleaned.groupby("number_of_promotions")["attrition"].mean(),
    title="Attrition vs Number of Promotions"
)
fig.show()

In [ ]:
fig = px.box(
    df_cleaned,
    x="attrition",
    y="monthly_income",
    title="Income Distribution: Stayed vs Left"
)
fig.show()

In [ ]:
# We group by the column and calculate the average (mean) of attrition (0 or 1)
age_attrition = df_cleaned.groupby('age_group', observed=False)['attrition'].mean().reset_index()
tenure_attrition = df_cleaned.groupby('tenure_group', observed=False)['attrition'].mean().reset_index()

# 2. Create subplots
fig = make_subplots(rows=1, cols=2,
                    subplot_titles=('Attrition Rate by Age Group', 'Attrition Rate by Tenure Group'))

# 3. Add Age Group bar trace
fig.add_trace(
    go.Bar(x=age_attrition['age_group'], y=age_attrition['attrition'],
           marker_color='blue', name='Age Group'),
    row=1, col=1
)

# 4. Add Tenure Group bar trace
fig.add_trace(
    go.Bar(x=tenure_attrition['tenure_group'], y=tenure_attrition['attrition'],
           marker_color='navy', name='Tenure Group'),
    row=1, col=2
)

fig.update_layout(height=500, width=1000, showlegend=False, template='plotly_white')
fig.update_yaxes(title_text="Proportion of Employees Left", row=1, col=1)
fig.update_yaxes(title_text="Proportion of Employees Left", row=1, col=2)

fig.show()

# 5 BUSINESS INSIGHTS💡


> 📌 Insight 1 — Work Environment Drives Attrition

Employees reporting poor or fair work-life balance show significantly higher attrition rates compared to those with good or excellent balance.
👉 This suggests that improving flexibility and workload distribution could reduce employee turnover.



> 📌 Insight 2 — Low Job Satisfaction is a Major Exit Driver

Attrition is strongly concentrated among employees with low and medium job satisfaction, indicating that dissatisfaction is a primary reason employees leave.
👉 HR should focus on engagement programs and feedback systems.


> 📌 Insight 3 — Salary & Promotions Matter

Employees with lower monthly income and fewer promotions are more likely to leave the company.
👉 This indicates a need for clearer career progression and competitive compensation strategies.



> 📌 Insight 4 — The "Mid-Career" Retention Cliff

Finding: Attrition peaks significantly among employees aged 30–44.
👉 Recommendation: This group is likely hitting a "development plateau." Implement targeted mid-level leadership training and mentorship programs to improve retention.


> 📌 Insight 5 — The "New Hire" Vulnerability

Finding: Employees in their first 2 years exhibit the highest turnover risk.
👉 Recommendation: The high departure rate suggests gaps in onboarding or culture fit. Introduce 90-day pulse checks and accelerated social integration initiatives to secure long-term commitment.

# Download the cleaned dataset 🔽

In [ ]:
from google.colab import files
df_cleaned.to_csv('cleaned.csv', index=False)
files.download('cleaned.csv')